
CREATE  TABLE ACCOUNTS(
    ACCOUNT_ID INTEGER  NOT NULL PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR  NOT NULL,
    CORRECT_BALANCE NUMERIC DEFAULT 0.0000,
    CREATED_AT TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
);